language: ruby
rvm: 2.4.1
git:
  depth: 1
before_install:
  - sudo add-apt-repository -y ppa:hyperair/zsh-backports # Trusty's zsh deos not support pipefail
  - sudo apt-get update
  - sudo apt-get install -y zsh
install: true
script: ruby --disable-gems ./test
